name: deploy-engine-to-vm

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - 'apps/execution-engine/**'
      - 'packages/nodes-base/**'
      - 'packages/db/**'
      - '.github/workflows/deploy-engine-to-vm.yml'
      - 'docker/Dockerfile.engine'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.engine
          push: true
          tags: |
            ikrambagban/nodeflow-engine:${{ github.sha }}
            ikrambagban/nodeflow-engine:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ikrambagban/nodeflow-engine:${{ github.sha }}
            docker network inspect nodeflow-network || docker network create nodeflow-network
            docker stop nodeflow-engine || true
            docker rm nodeflow-engine || true
            docker run -d \
              --name nodeflow-engine \
              --restart always \
              --network nodeflow-network \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -e NODE_ENV="production" \
              ikrambagban/nodeflow-engine:${{ github.sha }}
